### DISCUSSION TITLE
p.191 SECTION-073 DB接続用の環境変数名の差異

### DISCUSSION THREAD

**Discussion by ac0mz** [budougumi0617/go_todo_app#39] [Ideas]
まず p.185 SECTION-072 では、`docker-compose.yml`に `TODO_DB_DATABASE` という環境変数を定義しています。
```yml
services:
  app:
    ...

    environment:
      ...

      TODO_DB_HOST: todo-db
      TODO_DB_PORT: 3306
      TODO_DB_USER: todo
      TODO_DB_PASSWORD: todo
      TODO_DB_DATABASE: todo
```

しかし、p.191 SECTION-073 の`config/config.go`では`TODO_DB_DATABASE`ではなく、`TODO_DB_NAME`で環境変数名が定義されていました。
```go
type Config struct {
	...

	DBHost     string `env:"TODO_DB_HOST" envDefault:"127.0.0.1"`
	DBPort     int    `env:"TODO_DB_PORT" envDefault:"33306"`
	DBUser     string `env:"TODO_DB_USER" envDefault:"todo"`
	DBPassword string `env:"TODO_DB_PASS" envDefault:"todo"`
	DBName     string `env:"TODO_DB_NAME" envDefault:"todo"`
}
```

p.191には「docker-compose.ymlで定義したMySQL接続用の環境変数を読み込む」との記載がありますので、前提としてどちらも同一の環境変数を指しているならば、Config構造体側の定義を`TODO_DB_DATABASE`とする（またはyml側を変えて一致させる）のが正しいかと思われますが、認識合いますでしょうか？

もし同一だとして、環境変数名が合わずとも構造体のデフォルト値と環境変数がたまたま同値なので、よしなに動いてしまいますが😅
